# docker-bake.hcl — Docker Buildx Bake file for devpanel/php
#
# Build graph (→ = "depends on"):
#   phpX_Y-downloader              (GHCR registry-cached via mode=max, not pushed to Docker Hub)
#     └─▶ phpX_Y-php-ext           (GHCR registry-cached via mode=max, not pushed to Docker Hub)
#           └─▶ phpX_Y-base        (GHCR registry-cached, pushed to Docker Hub)
#                 └─▶ phpX_Y-secure-int  (GHCR registry-cached via mode=max, not pushed to Docker Hub)
#                       └─▶ phpX_Y-secure    (GHCR registry-cached, pushed to Docker Hub)
#                             └─▶ phpX_Y-advance  (GHCR registry-cached, pushed to Docker Hub)
#
# Key variables (all overridable via environment variables):
#   REPO                          Docker Hub repository                        (devpanel/php)
#   GHCR_REPO                     GitHub Container Registry repository         (ghcr.io/devpanel/php)
#   TAG_SUFFIX                    Image tag suffix                             ("" on main, "-rc" on develop)
#   VERSIONS                      Space-separated PHP version dirs             ("7.4 8.0 8.1 8.2 8.3")
#   DOWNLOADS_DIR                 Path to pre-seeded artifacts directory       ("" = download in Dockerfile)
#   CORERULESET_VERSION           ModSecurity CRS version                      (3.3.5)
#   CACHE_FROM_ENABLED            Read from GHA/GHCR cache ("true"/"false")    ("true")
#   PLATFORMS                     Comma-separated target platforms             ("linux/amd64,linux/arm64")
#   VERSIONS_NEEDING_MULTIPART_FIX  Versions running Debian 11 / modsec 2.9.3  ("7.4 8.0")
#
# Per-version code-server and Copilot Chat build args are NOT global bake
# variables.  In CI they are injected per-target via a JSON bake-override file
# generated by the preseed-downloads composite action (one entry per
# phpX_Y-downloader target).  For standalone local builds the Dockerfile ARG
# defaults are used as fallback.
#
# Cache behavior depends on GHCR_WRITABLE.  When GHCR_WRITABLE=true, all
# targets use GHCR registry cache (type=registry, mode=max) as the sole
# durable cache store; GHA cache writes are skipped so that GHA cache quota
# is preserved for other workflow caches (e.g. dependency caches).  When
# GHCR_WRITABLE=false, both GHCR and GHA are used as best-effort caches
# (ignore-error=true for both).  Intermediate targets (downloader, php-ext,
# secure-int) participate in that GHCR-backed registry cache as build cache
# only; this bake file does not publish them as standalone GHCR images.
# GHA cache eviction ("cache entry no longer exists") is non-fatal for all
# targets.

# ─── Default group ───────────────────────────────────────────────────────────
# Running `docker buildx bake` without arguments builds this group.
# All three stage groups are listed explicitly: Docker Buildx Bake only pushes
# images that belong to a target listed in the group being built.  Targets that
# are used only as named build contexts (context dependencies) are built but
# never pushed, even when they carry tags.  Listing php-base and php-secure
# here ensures they are treated as first-class push targets.
# VERSIONS_BASE / VERSIONS_SECURE control which versions are tagged and pushed
# to Docker Hub for the base / secure stages respectively (via should_push()).
# Versions absent from those lists are still built (they are required by the
# advance dependency chain) but produce no Docker Hub tags and are not pushed.
# No per-version target names are passed as CLI arguments, which avoids the
# bake v0.31+ restriction on resolving matrix-generated names.
group "default" {
  targets = ["php-base", "php-secure", "php-advance"]
}

variable "REPO"                          { default = "devpanel/php"            }
# GHCR_REPO is overridden in CI via the GHCR_REPO env variable (see workflow files).
# The default below is a convenience fallback for local development only.
variable "GHCR_REPO"                     { default = "ghcr.io/devpanel/php"    }
variable "TAG_SUFFIX"                    { default = ""                        }
variable "VERSIONS"                      { default = "7.4 8.0 8.1 8.2 8.3"    }
# VERSIONS_BASE / VERSIONS_SECURE: subsets of VERSIONS for which the base /
# secure final images should be tagged and pushed to Docker Hub.  Both default
# to the full VERSIONS set so a plain `docker buildx bake` pushes everything.
# CI narrows these to only the versions whose files actually changed.
variable "VERSIONS_BASE"                 { default = "7.4 8.0 8.1 8.2 8.3"    }
variable "VERSIONS_SECURE"               { default = "7.4 8.0 8.1 8.2 8.3"    }

variable "CORERULESET_VERSION"           { default = "3.3.5"                   }
# DOWNLOADS_DIR: path to a directory whose pre-downloaded/ subdirectory contains
# pre-seeded build artifacts (code-server .deb files and Copilot Chat VSIX).
# When set by CI to a runner-local path pre-populated by actions/cache@v5, the
# downloader stage bind-mounts /pre-downloaded from it instead of downloading.
# When empty (default), no named context override is provided and the Dockerfile's
# 'downloads' stage (FROM alpine:3 with an empty /pre-downloaded dir) is used,
# causing all downloads to fall through to the normal network path.
variable "DOWNLOADS_DIR"                 { default = ""                        }
variable "CACHE_FROM_ENABLED"            { default = "true"                    }
# GHCR_WRITABLE is set by the detect-versions action (runs once centrally
# in the detect job) and propagated to each build job via the build matrix.
# "true"  → GHCR cache writes proceed without ignore-error (write expected to
#            succeed) and GHA cache writes are skipped entirely so that GHA
#            cache quota is preserved for other caches in the workflow.
# "false" → GHCR cache writes use ignore-error=true; GHA cache is also written
#            as a best-effort fallback (ignore-error=true).
# Default is "false" so that local dev builds (where no pre-flight check runs)
# never abort due to a GHCR write failure.
variable "GHCR_WRITABLE"                { default = "false"                   }
variable "PLATFORMS"                     { default = "linux/amd64,linux/arm64" }
# PUSH_BY_DIGEST: when "true" final images are pushed by content-hash with no
# tag.  A separate manifest-merge step then creates / updates the tagged
# multi-arch manifest.  Intermediate targets (downloader, php-ext, secure-int)
# are unaffected by this flag; their layers are exported to GHCR via
# type=registry,mode=max cache and they are never pushed to Docker Hub.
# Default is "false" so that local builds and test runs (using --load) work
# without needing a real registry.  The build-php-images CI action always sets
# this to "true" to enable the progressive-manifest merge pipeline.
variable "PUSH_BY_DIGEST"               { default = "false"                   }
# PLATFORM_KEY: when non-empty, cache scopes and GHCR cache refs are suffixed
# with "-${PLATFORM_KEY}" to isolate each platform's GHA/GHCR cache entries.
# This prevents cache thrashing when multiple per-platform jobs for the same PHP
# version run concurrently (e.g. amd64 + arm64 in the build matrix).  Set by
# build-php-images from inputs.platform (e.g. "linux-amd64").  Defaults to ""
# so that local multi-platform builds share a single cache entry as before.
variable "PLATFORM_KEY"                  { default = ""                        }
# Versions using Debian 11 / mod_security 2.9.3 that require the
# REQUEST-922-MULTIPART-ATTACK rule to be removed.
variable "VERSIONS_NEEDING_MULTIPART_FIX" { default = "7.4 8.0" }

# ─── Cache helpers ────────────────────────────────────────────────────────────
# cache_from_registry / cache_to_registry: GHCR registry cache (used by all targets).
#   When GHCR is writable it is the sole cache_to destination (no GHA write).
#   When GHCR is not writable, both GHCR and GHA are written as best-effort.

# ver_key: converts a version string ("8.1") to a key safe for target names ("8_1").
# Dots are not valid in HCL identifiers (they are the attribute-access operator),
# so they must be replaced. Underscores are used rather than simply removing the
# dot to avoid ambiguity when major versions reach two digits
# (e.g. "10.1" → "10_1" is distinct from a hypothetical "1.01" → "1_01").
function "ver_key" {
  params = [v]
  result = replace(v, ".", "_")
}

# plat_sfx: returns "-${PLATFORM_KEY}" when PLATFORM_KEY is set, "" otherwise.
# Appended to cache scope names and GHCR cache refs to keep each platform's
# GHA / GHCR cache entries separate when the build matrix runs one job per platform.
function "plat_sfx" {
  params = []
  result = PLATFORM_KEY != "" ? "-${PLATFORM_KEY}" : ""
}

# should_push: true if version v is listed in the space-separated stage_versions
# string.  Used to make Docker Hub tags conditional: targets whose version is not
# in the per-stage list are still built (for the dependency chain / GHCR cache)
# but are not tagged and therefore not pushed to Docker Hub.
function "should_push" {
  params = [stage_versions, v]
  result = contains(split(" ", trimspace(stage_versions)), v)
}

# cache_to_registry: writes GHCR registry cache and, when GHCR is not writable,
# also writes GHA cache.  All targets use this function.  GHA cache writes are
# only used as a fallback (GHCR_WRITABLE=false) so that GHA cache quota is not
# consumed when GHCR is available.  GHA cache writes always use ignore-error=true
# because GHA cache eviction ("cache entry no longer exists") is a transient
# failure mode that should never abort the build.  GHCR write strictness depends
# on GHCR_WRITABLE:
#   GHCR_WRITABLE=true  → GHCR only (no ignore-error; GHA skipped to save cache quota)
#   GHCR_WRITABLE=false → GHCR best-effort (ignore-error=true) + GHA best-effort (ignore-error=true)
#
# cache_from_registry reads from the GHCR branch-specific ref and, when TAG_SUFFIX
# is non-empty (i.e. not on main), also reads from main's cache ref so that layers
# built by a main-branch CI run are reusable on any other branch.  GHA cache is
# always included as an additional source.  sibling branches cannot share
# actions/cache entries (scoped per branch), but the GHCR registry cache is not
# subject to that restriction.
#
# main_cache_ref: strips TAG_SUFFIX from the image tag portion of a GHCR ref,
# yielding the main-branch equivalent ref.  A greedy regex extracts everything
# up to the last ":" as the registry+path component and everything after as the
# tag, so refs with a port in the hostname (e.g. localhost:5000/repo:tag) are
# handled correctly.  The TAG_SUFFIX is appended once by the detect step, so a
# plain replace on the tag portion always removes exactly one occurrence.

function "main_cache_ref" {
  params = [ref]
  # Strips TAG_SUFFIX from only the tag portion of ref (everything after the
  # last ":"), keeping the registry/path portion unchanged even if it happens
  # to contain the same string.  HCL functions have no local variables, so
  # regex() is evaluated twice; the identical calls are intentional.
  result = join(":", [
    regex("^(.+):([^:]+)$", ref)[0],
    replace(regex("^(.+):([^:]+)$", ref)[1], TAG_SUFFIX, "")
  ])
}

function "cache_from_registry" {
  params = [ref, scope]
  result = CACHE_FROM_ENABLED == "true" ? concat(
    ["type=registry,ref=${ref}"],
    TAG_SUFFIX != "" ? ["type=registry,ref=${main_cache_ref(ref)}"] : [],
    ["type=gha,scope=${scope}"]
  ) : []
}

function "cache_to_registry" {
  params = [ref, scope]
  result = GHCR_WRITABLE == "true" ? [
    "type=registry,ref=${ref},mode=max"
  ] : [
    "type=registry,ref=${ref},mode=max,ignore-error=true",
    "type=gha,scope=${scope},mode=max,ignore-error=true"
  ]
}

# ─── Per-version downloader targets (registry-cached in GHCR, NOT pushed to Docker Hub) ─
# Each PHP version has its own downloader that runs inside php:${PHP_VERSION}-apache,
# which uses the correct Debian release for that PHP version.  In CI the code-server
# and Copilot Chat build args (CODESERVER_VERSION, CODESERVER_DEB_SHA256_AMD64/ARM64,
# COPILOT_CHAT_VERSION, COPILOT_CHAT_VSIX_SHA256) are injected per-target via a JSON
# bake-override file generated by the preseed-downloads composite action.  That action
# detects each version's Debian codename at runtime and resolves the newest compatible
# binary for it — no hardcoded Debian version names anywhere in this file.
# For standalone local builds the Dockerfile ARG defaults are used as fallback.
#
# Matrix generates one target per version: php7_4-downloader, php8_0-downloader, ...

target "_downloader-common" {
  dockerfile = "Dockerfile"
  context    = "base"
  target     = "downloader"
  platforms  = split(",", PLATFORMS)
  # When DOWNLOADS_DIR is set, override the 'downloads' named context with that
  # directory so Docker uses pre-seeded files instead of downloading from the
  # internet.  When empty (default), no override is provided and the Dockerfile's
  # 'downloads' stage (FROM alpine:3 with an empty /pre-downloaded dir) is used,
  # causing all downloads to fall through to the normal network path.
  contexts = DOWNLOADS_DIR != "" ? { downloads = DOWNLOADS_DIR } : {}
}

target "php-downloader" {
  matrix = {
    version = split(" ", trimspace(VERSIONS))
  }
  name       = "php${ver_key(version)}-downloader"
  inherits   = ["_downloader-common"]
  args       = { PHP_VERSION = version }
  tags       = ["${GHCR_REPO}:${version}-downloader${TAG_SUFFIX}"]
  cache-from = cache_from_registry("${GHCR_REPO}:cache-${version}-downloader${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-downloader${plat_sfx()}")
  cache-to   = cache_to_registry("${GHCR_REPO}:cache-${version}-downloader${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-downloader${plat_sfx()}")
}

# ─── Common php-ext intermediates (registry-cached in GHCR, NOT pushed to Docker Hub) ─
# Builds the php-ext-common stage from base/Dockerfile for each PHP version.
# Contains all extensions, packages, and tools common to every version.
# Version-specific differences (avif, pcre, gd flags, imagick method, etc.)
# are in each {version}/base/Dockerfile.
#
# Matrix generates one target per version: php7_4-php-ext, php8_0-php-ext, ...

target "_php-ext-common" {
  dockerfile = "Dockerfile"
  target     = "php-ext-common"
  context    = "base"
  contexts = {
    common = "./base"
  }
  platforms  = split(",", PLATFORMS)
  # No tags → not pushed to Docker Hub
}

target "php-php-ext" {
  matrix = {
    version = split(" ", trimspace(VERSIONS))
  }
  name     = "php${ver_key(version)}-php-ext"
  inherits = ["_php-ext-common"]
  args     = { PHP_VERSION = version }
  contexts = {
    common-downloader = "target:php${ver_key(version)}-downloader"
  }
  tags       = ["${GHCR_REPO}:${version}-php-ext${TAG_SUFFIX}"]
  cache-from = cache_from_registry("${GHCR_REPO}:cache-${version}-php-ext${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-php-ext${plat_sfx()}")
  cache-to   = cache_to_registry("${GHCR_REPO}:cache-${version}-php-ext${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-php-ext${plat_sfx()}")
}

# ─── Base final images ────────────────────────────────────────────────────────
# Each version has its own Dockerfile containing only version-specific
# differences (gd/avif, pcre, PECL extensions, tool version overrides).
# 'common-php-ext' provides the shared php-ext intermediate without a registry
# push.  'common-downloader' provides code-server .deb.  'common' exposes
# ./base/ for any remaining shared assets.

target "_base-common" {
  platforms  = split(",", PLATFORMS)
}

target "php-base" {
  matrix = {
    version = split(" ", trimspace(VERSIONS))
  }
  name       = "php${ver_key(version)}-base"
  inherits   = ["_base-common"]
  dockerfile = "Dockerfile"
  context    = "${version}/base"
  contexts = {
    common-php-ext    = "target:php${ver_key(version)}-php-ext"
    common-downloader = "target:php${ver_key(version)}-downloader"
    common            = "./base"
  }
  # Normal mode (default): push directly to the named tag on Docker Hub.
  # Digest mode (CI): push by content-hash only (no tag); a separate merge
  # step creates / updates the tagged multi-arch manifest list.
  # When GHCR is writable a second output to GHCR is added so that the
  # merge-manifests step can source refs from GHCR instead of Docker Hub,
  # avoiding authenticated Docker Hub pull quota for imagetools create.
  # When GHCR is not writable only the Docker Hub output is emitted (fallback).
  tags   = PUSH_BY_DIGEST != "true" && should_push(VERSIONS_BASE, version) ? ["${REPO}:${version}-base${TAG_SUFFIX}"] : []
  output = PUSH_BY_DIGEST == "true" && should_push(VERSIONS_BASE, version) ? concat(
    ["type=image,name=${REPO},push-by-digest=true,name-canonical=true,push=true"],
    GHCR_WRITABLE == "true" ? ["type=image,name=${GHCR_REPO},push-by-digest=true,name-canonical=true,push=true"] : []
  ) : []
  cache-from = cache_from_registry("${GHCR_REPO}:cache-${version}-base${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-base${plat_sfx()}")
  cache-to   = cache_to_registry("${GHCR_REPO}:cache-${version}-base${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-base${plat_sfx()}")
}

# ─── Secure intermediate targets (registry-cached in GHCR, NOT pushed to Docker Hub) ──
# Built from the secure-intermediate stage of secure/Dockerfile on top of each
# version's base image.

target "_secure-int-common" {
  dockerfile = "Dockerfile"
  target     = "secure-intermediate"
  context    = "secure"
  platforms  = split(",", PLATFORMS)
  args       = { BASE_IMAGE = "base-image", CORERULESET_VERSION = CORERULESET_VERSION }
  # No tags → not pushed to Docker Hub
}

target "php-secure-int" {
  matrix = {
    version = split(" ", trimspace(VERSIONS))
  }
  name     = "php${ver_key(version)}-secure-int"
  inherits = ["_secure-int-common"]
  contexts = { base-image = "target:php${ver_key(version)}-base" }
  tags       = ["${GHCR_REPO}:${version}-secure-int${TAG_SUFFIX}"]
  cache-from = cache_from_registry("${GHCR_REPO}:cache-${version}-secure-int${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-secure-int${plat_sfx()}")
  cache-to   = cache_to_registry("${GHCR_REPO}:cache-${version}-secure-int${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-secure-int${plat_sfx()}")
}

# ─── Secure final images ──────────────────────────────────────────────────────
# Versions in VERSIONS_NEEDING_MULTIPART_FIX (7.4 and 8.0) use a per-version
# Dockerfile to remove the REQUEST-922-MULTIPART-ATTACK rule (mod_security 2.9.3
# on Debian 11 doesn't support it).  All other versions use the shared 'final'
# stage from secure/Dockerfile, which just inherits USER/WORKDIR/CMD from the
# secure-intermediate without adding new layers.

target "_secure-common" {
  platforms  = split(",", PLATFORMS)
  args       = { BASE_IMAGE = "secure-intermediate" }
  target     = "final"
}

target "php-secure" {
  matrix = {
    version = split(" ", trimspace(VERSIONS))
  }
  name       = "php${ver_key(version)}-secure"
  inherits   = ["_secure-common"]
  dockerfile = "Dockerfile"
  context    = contains(split(" ", VERSIONS_NEEDING_MULTIPART_FIX), version) ? "${version}/secure" : "secure"
  contexts   = { secure-intermediate = "target:php${ver_key(version)}-secure-int" }
  # Normal mode (default): push directly to the named tag on Docker Hub.
  # Digest mode (CI): push by content-hash only (no tag); a separate merge
  # step creates / updates the tagged multi-arch manifest list.
  # When GHCR is writable a second output to GHCR is added so that the
  # merge-manifests step can source refs from GHCR instead of Docker Hub,
  # avoiding authenticated Docker Hub pull quota for imagetools create.
  # When GHCR is not writable only the Docker Hub output is emitted (fallback).
  tags   = PUSH_BY_DIGEST != "true" && should_push(VERSIONS_SECURE, version) ? ["${REPO}:${version}-secure${TAG_SUFFIX}"] : []
  output = PUSH_BY_DIGEST == "true" && should_push(VERSIONS_SECURE, version) ? concat(
    ["type=image,name=${REPO},push-by-digest=true,name-canonical=true,push=true"],
    GHCR_WRITABLE == "true" ? ["type=image,name=${GHCR_REPO},push-by-digest=true,name-canonical=true,push=true"] : []
  ) : []
  cache-from = cache_from_registry("${GHCR_REPO}:cache-${version}-secure${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-secure${plat_sfx()}")
  cache-to   = cache_to_registry("${GHCR_REPO}:cache-${version}-secure${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-secure${plat_sfx()}")
}

# ─── Advance final images ─────────────────────────────────────────────────────
# All versions use the same advance/Dockerfile; only the base image differs.

target "_advance-common" {
  dockerfile = "Dockerfile"
  context    = "advance"
  platforms  = split(",", PLATFORMS)
  args       = { BASE_IMAGE = "base-image" }
}

target "php-advance" {
  matrix = {
    version = split(" ", trimspace(VERSIONS))
  }
  name     = "php${ver_key(version)}-advance"
  inherits = ["_advance-common"]
  contexts = { base-image = "target:php${ver_key(version)}-secure" }
  # Normal mode (default): push directly to the named tag on Docker Hub.
  # Digest mode (CI): push by content-hash only (no tag); a separate merge
  # step creates / updates the tagged multi-arch manifest list.
  # When GHCR is writable a second output to GHCR is added so that the
  # merge-manifests step can source refs from GHCR instead of Docker Hub,
  # avoiding authenticated Docker Hub pull quota for imagetools create.
  # When GHCR is not writable only the Docker Hub output is emitted (fallback).
  tags   = PUSH_BY_DIGEST != "true" ? ["${REPO}:${version}-advance${TAG_SUFFIX}"] : []
  output = PUSH_BY_DIGEST == "true" ? concat(
    ["type=image,name=${REPO},push-by-digest=true,name-canonical=true,push=true"],
    GHCR_WRITABLE == "true" ? ["type=image,name=${GHCR_REPO},push-by-digest=true,name-canonical=true,push=true"] : []
  ) : []
  cache-from = cache_from_registry("${GHCR_REPO}:cache-${version}-advance${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-advance${plat_sfx()}")
  cache-to   = cache_to_registry("${GHCR_REPO}:cache-${version}-advance${plat_sfx()}${TAG_SUFFIX}", "php${ver_key(version)}-advance${plat_sfx()}")
}
