name: Docker build and push PHP8.0-secure

on:
  push:
    paths:
      - "8.0/secure/**"
    branches:
      - main
      - develop
  workflow_run:
    workflows: ["Docker build and push PHP8.0-base"]
    branches:
      - main
      - develop
    types:
      - completed
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to testing environment
        if:  ${{ github.event.workflow_run.head_branch == 'develop' }}
        run: |
          echo "IMAGE_TAG=devpanel/php:8.0-secure-rc" >> $GITHUB_ENV

      - name: Set env to production environment
        if: ${{ github.event.workflow_run.head_branch == 'main' }}
        run: |
          echo "IMAGE_TAG=devpanel/php:8.0-secure" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./8.0/secure/Dockerfile
          context: ./8.0/secure/
          push: true
          tags: ${{ env.IMAGE_TAG }}
