name: Docker build and push PHP7.4-base

env:
  DOCKER_BUILDKIT: 1
  IMAGE_TAG: devpanel/php:7.4-base-rc
  
on:
  push:
    paths:
      - "7.4/base/**"
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  docker:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Set env to production environment
        if: endsWith(github.ref, '/main')
        run: |
          echo "IMAGE_TAG=devpanel/php:7.4-base" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./7.4/base/Dockerfile
          context: ./7.4/base/
          push: true
          tags: ${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
